name: Deploy an Azure Container Instance to a Virtual Network

on:
    issue_comment:
        types: [created]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            
            - uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}
            


